sudo: required
language: python
git:
  depth: 10
  quiet: true
services:
  - docker
python:
  - "2.7"
  - "3.6"
env:
  global:
    - T2T_PROBLEM=algorithmic_reverse_binary40_test
    - T2T_DATA_DIR=/tmp/t2t-data
    - T2T_TRAIN_DIR=/tmp/t2t-train
    - TF_LATEST="1.11.*"
    # This is necessary to have gsutil work with Python 2.7
    - BOTO_CONFIG=/dev/null
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.
    # If updating, also update TF_LATEST above
    - TF_VERSION="1.10.*"
    - TF_VERSION="1.11.*"
    - TF_VERSION="tf-nightly"
matrix:
  exclude:
    # We test against all versions in Python 2 but only the latest in Python 3
    - python: "3.6"
      env: TF_VERSION="1.10.*"
    - python: "3.6"
      env: TF_VERSION="tf-nightly"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-dev
install:
  - ./oss_scripts/oss_pip_install.sh
  - pip install -q flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - if [[ $TRAVIS_PYTHON_VERSION == '3.*' ]]; then flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics; fi
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - if [[ $TF_VERSION == "1.10.*" ]]; then flake8 . --count --exit-zero --ignore=E111,E114 --max-complexity=10 --max-line-length=127 --statistics; fi
script:
  - ./oss_scripts/oss_tests.sh
  - ./oss_scripts/oss_integration_test.sh

  # Conditional commands should each be in a separate block to get proper
  # errors on Travis.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] && [[ "$TF_VERSION" == "tf-nightly"  ]]; then
        pylint -j 2 tensor2tensor;
    fi
